version: "3.3"

services:

  backend:
    image: sudoku-backend
    runtime: nvidia
    build:
      context: .
      dockerfile: backend/Dockerfile

    volumes:
      - ${PWD}/models:/backend/models
      - ${PWD}/fonts:/backend/fonts

    #ports:
      #- 5000:5000

  frontend:
    image: sudoku-frontend
    build:
      context: frontend
      dockerfile: Dockerfile

    ports:
      - 8080:8080
